apiVersion: v1
data:
  keys.txt: IyBjcmVhdGVkOiAyMDI0LTAyLTIyVDEyOjQyOjMwKzAxOjAwCiMgcHVibGljIGtleTogYWdlMW05YTJ1dmsyZHQ4MHh0c2N2bXpmcHJtMno2NHNrYTBsc3NjM3JrMmg2dHNtc3NsdzM5anNsZWQzeDcKQUdFLVNFQ1JFVC1LRVktMVc1OVg2MEtUWlIyMkdUNFJXMzhKVk41QUhRTkVLVERYR1c4MkxSN1dYREhMRTMyRUVZN1FOVjBaODgK
kind: Secret
metadata:
  creationTimestamp: null
  name: sops-age
  namespace: argocd
