apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app
    spec:
      containers:
        - name: {{ .Release.Name }}-container
          image: nginxa
          env:
            - name: MY_VARIABLE
              value: {{ .Values.myvariable }}
          volumeMounts:
            - name: appsettings-volume
              mountPath: "/app/appsettings.json"
              subPath: appsettings.json
      volumes:
        - name: appsettings-volume
          secret:
            secretName: {{ .Release.Name }}-appsettings